# Generated by Django 4.2.5 on 2023-09-17 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0004_deudacliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeudaCliente',
        ),
    ]
