# Generated by Django 4.2.5 on 2023-09-18 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0005_delete_deudacliente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Socio',
            new_name='Servicios',
        ),
    ]
