# Generated by Django 4.2.5 on 2023-09-19 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0006_rename_socio_servicios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicios',
            old_name='apellido',
            new_name='Servicio',
        ),
    ]
