# Generated by Django 4.2.5 on 2023-09-19 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0007_rename_apellido_servicios_servicio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipo',
            new_name='Equipos',
        ),
    ]
